//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMateWeb.Dal.DataCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuspendItem
    {
        public int Id { get; set; }
        public int PosItemId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public System.DateTime SuspensionTime { get; set; }
        public bool IsActive { get; set; }
        public string ItemName { get; set; }
        public int StaffId { get; set; }
    }
}
